Update

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -68,6 +68,19 @@ jobs:
                 curl -f -L "$url" >> Tool-repo/Ruleset/CDN.list || { echo "Download Failed: $url"; exit 1; }
                 echo "" >> Tool-repo/Ruleset/CDN.list
             done
+            # 合并 SukkaW Download 规则
+            urls=(
+                "https://ruleset.skk.moe/List/non_ip/microsoft_cdn.conf"
+                "https://ruleset.skk.moe/List/non_ip/download.conf"
+                "https://ruleset.skk.moe/List/domainset/download.conf"
+                "https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Custom/Direct.list"
+            )
+            > Tool-repo/Ruleset/Direct.list
+            for url in "${urls[@]}"; do
+                echo "Downloading: $url"
+                curl -f -L "$url" >> Tool-repo/Ruleset/Direct.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/Direct.list
+            done
             # 合并 GFW 规则
             urls=(
                 "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
